/**
 * Live check against Lichess: runs the real fetch plan the way puzzleStore does and reports
 * per-batch yield, bucket fill and total wall time. Not part of the app bundle.
 *
 *   npx tsx scripts/verify-puzzle-sync.ts
 */
import {
  FULL_SYNC_FETCH_PLAN,
  PuzzleRateLimitError,
  TARGET_PER_BUCKET,
  TOTAL_SYNC_STEPS,
  bucketCounts,
  countByAppDifficulty,
  fetchPuzzleStep,
  mergeWithBucketCaps,
  stepKey,
} from '../src/services/puzzleFetcher';
import type { Puzzle } from '../src/types/puzzle';

async function main() {
  const started = Date.now();
  let puzzles: Puzzle[] = [];
  let rateLimited = false;

  for (let i = 0; i < TOTAL_SYNC_STEPS; i++) {
    const step = FULL_SYNC_FETCH_PLAN[i];
    const t = Date.now();
    try {
      const batch = await fetchPuzzleStep(step, 50);
      const before = puzzles.length;
      puzzles = mergeWithBucketCaps(puzzles, batch);
      console.log(
        `batch ${i + 1}/${TOTAL_SYNC_STEPS} ${stepKey(step).padEnd(18)} returned=${String(batch.length).padStart(2)} kept=${String(puzzles.length - before).padStart(2)} total=${String(puzzles.length).padStart(3)} ${Date.now() - t}ms`,
      );
    } catch (error) {
      const limited = error instanceof PuzzleRateLimitError;
      if (limited) rateLimited = true;
      console.log(
        `batch ${i + 1}/${TOTAL_SYNC_STEPS} ${stepKey(step).padEnd(18)} FAILED ${limited ? 'RATE LIMITED' : (error as Error).message}`,
      );
      if (limited) break;
    }
  }

  console.log(`\nwall time: ${((Date.now() - started) / 1000).toFixed(1)}s   rate limited: ${rateLimited}`);
  console.log('by app difficulty:', countByAppDifficulty(puzzles));

  const counts = bucketCounts(puzzles);
  const filled = Object.entries(counts).filter(([, n]) => n >= TARGET_PER_BUCKET).length;
  console.log('buckets (mateIn:difficulty):', counts);
  console.log(`buckets at target: ${filled}/9`);
  console.log(`TOTAL PUZZLES: ${puzzles.length}`);

  if (process.argv.includes('--emit') && filled === 9) {
    await writeSeedPack(puzzles);
  } else if (process.argv.includes('--emit')) {
    console.log('\nnot emitting seed pack — buckets incomplete');
  }
}

/**
 * Writes the bundled pack. Sorted by bucket so the diff is reviewable, and re-running only
 * changes the file when the puzzles actually change.
 */
async function writeSeedPack(puzzles: Puzzle[]) {
  const order = { beginner: 0, club: 1, master: 2 } as const;
  const sorted = [...puzzles].sort(
    (a, b) => order[a.difficulty] - order[b.difficulty] || a.mateIn - b.mateIn || a.id.localeCompare(b.id),
  );

  const body = `import type { Puzzle } from '@/types/puzzle';

/**
 * Bundled puzzle library — 20 puzzles per mate-in × difficulty bucket, taken from the Lichess
 * public puzzle database (CC0). Generated by scripts/verify-puzzle-sync.ts --emit; do not edit.
 *
 * An alarm must be able to show a puzzle with no network: Lichess rate limits by IP, and mobile
 * carriers put many subscribers behind one address, so a fresh install can be throttled by
 * traffic that is not ours.
 */
export const seedPuzzlePack: Puzzle[] = ${JSON.stringify(sorted, null, 2)};
`;

  const target = new URL('../src/puzzles/seedPack.ts', import.meta.url);
  const { writeFile } = await import('node:fs/promises');
  await writeFile(target, body, 'utf8');
  console.log(`\nwrote ${sorted.length} puzzles to src/puzzles/seedPack.ts`);
}

main();
